## Getting the city information using API

list of API from Github: https://github.com/public-apis/public-apis

In [1]:
import pandas as pd
import requests
import time
from bs4 import BeautifulSoup
import re
from sqlalchemy import text
from datetime import datetime

The disply functions

In [2]:
pd.set_option("display.width", 1000)
pd.set_option("display.max_columns", None)

In [3]:
# Creating a for loop that will go over Germany's 5 largest cities, retrieving API info for each one
german_cities = ['Berlin', 'Hamburg', 'Frankfurt', 'Munich', 'Cologne']
cities_json = []     # Empty list, on each iteration we will add the current API response to it

for german_city in german_cities:
  url = "https://api.api-ninjas.com/v1/city"
  header={"X-Api-Key": "YOUR_API_NINJAS_KEY"}
  querystring = {"country" : "DE", "name" : german_city}   # Passing the current iteration city name as the value in the 'querystring' dictionary
  city_request = requests.request("GET", url, headers=header, params=querystring)
  city_json = city_request.json()
  cities_json += city_json    # Adding current iteration response to list of responses from all cities together, using '+' to add lists to one another

cities_json

[{'name': 'Berlin',
  'latitude': 52.5167,
  'longitude': 13.3833,
  'country': 'DE',
  'population': 3644826,
  'region': 'N/A',
  'is_capital': True},
 {'name': 'Hamburg',
  'latitude': 53.55,
  'longitude': 10.0,
  'country': 'DE',
  'population': 1841179,
  'region': 'N/A',
  'is_capital': False},
 {'name': 'Frankfurt',
  'latitude': 50.1136,
  'longitude': 8.6797,
  'country': 'DE',
  'population': 753056,
  'region': 'Hesse',
  'is_capital': False},
 {'name': 'Munich',
  'latitude': 48.1372,
  'longitude': 11.5755,
  'country': 'DE',
  'population': 1471508,
  'region': 'Bavaria',
  'is_capital': False},
 {'name': 'Cologne',
  'latitude': 50.9422,
  'longitude': 6.9578,
  'country': 'DE',
  'population': 1085664,
  'region': 'North Rhine-Westphalia',
  'is_capital': False}]

In [4]:
cities_df = pd.DataFrame(cities_json)
cities_df

        name  latitude  longitude country  population                  region  is_capital
0     Berlin   52.5167    13.3833      DE     3644826                     N/A        True
1    Hamburg   53.5500    10.0000      DE     1841179                     N/A       False
2  Frankfurt   50.1136     8.6797      DE      753056                   Hesse       False
3     Munich   48.1372    11.5755      DE     1471508                 Bavaria       False
4    Cologne   50.9422     6.9578      DE     1085664  North Rhine-Westphalia       False

#### Droping region and is_capital

In [5]:
cities_df = cities_df.drop(columns=["region", "is_capital"])
cities_df.head()

        name  latitude  longitude country  population
0     Berlin   52.5167    13.3833      DE     3644826
1    Hamburg   53.5500    10.0000      DE     1841179
2  Frankfurt   50.1136     8.6797      DE      753056
3     Munich   48.1372    11.5755      DE     1471508
4    Cologne   50.9422     6.9578      DE     1085664

#### Now making two tables like we did during scrapping

In [6]:
cities_list = cities_df.loc[:, 'name'] 
cities_list = pd.DataFrame(cities_list)
cities_list

        name
0     Berlin
1    Hamburg
2  Frankfurt
3     Munich
4    Cologne

In [7]:
fact_list = cities_df.copy()
fact_list

        name  latitude  longitude country  population
0     Berlin   52.5167    13.3833      DE     3644826
1    Hamburg   53.5500    10.0000      DE     1841179
2  Frankfurt   50.1136     8.6797      DE      753056
3     Munich   48.1372    11.5755      DE     1471508
4    Cologne   50.9422     6.9578      DE     1085664

#### Now pushing this data frame into the SQL database (cities_list and fact_list)

In [8]:
import pandas as pd
from sqlalchemy import create_engine

# Update with your correct schema name
schema = "County_city_info_API"
host = "127.0.0.1"
user = "root"
password = "YOUR_DB_PASSWORD"
port = 3306

# Establish the connection string
connection_string = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

# Create the engine object (Required for modern Pandas to_sql)
engine = create_engine(connection_string)

# Establish connection engine
schema = "County_city_info_API"
connection_string = f'mysql+pymysql://root:YOUR_DB_PASSWORD@127.0.0.1:3306/{schema}'
engine = create_engine(connection_string)

# step 1: Pushing the cities_list into the SQL database
cities_list.to_sql('city_list', if_exists='append', con=engine, index=False)
print("✅ Data successfully appended! MySQL handled the auto-increment keys.")

✅ Data successfully appended! MySQL handled the auto-increment keys.

Now linking the autogenerated city_id in SQL to the fact_list using city as common table.

In [9]:
# Step 2: Fetch the official auto-generated IDs directly from your new database layout
# The SQL table is 'cities_list' and the column is 'name'
query = text("SELECT city_id, name FROM city_list")
db_cities = pd.read_sql(query, con=engine)
db_cities

   city_id       name
0        1     Berlin
1        2    Hamburg
2        3  Frankfurt
3        4     Munich
4        5    Cologne

In [10]:
# Step 3: Create an automated dictionary mapping tool in Python
# We map the database 'name' column to 'city_id'
city_to_id_map = dict(zip(db_cities['name'], db_cities['city_id']))
# Step 4: Create a clean copy of your local data frame to protect your original variable
# Using 'fact_list' as your source dataframe
upload_df_fact = fact_list.copy()
# Step 5: Map your text names to the official database IDs to lock in the Foreign Key
# Changed 'City' to 'name' to match your current dataframe column
upload_df_fact['city_id'] = upload_df_fact['name'].map(city_to_id_map)
upload_df_fact

        name  latitude  longitude country  population  city_id
0     Berlin   52.5167    13.3833      DE     3644826        1
1    Hamburg   53.5500    10.0000      DE     1841179        2
2  Frankfurt   50.1136     8.6797      DE      753056        3
3     Munich   48.1372    11.5755      DE     1471508        4
4    Cologne   50.9422     6.9578      DE     1085664        5

In [11]:
 upload_df_fact.drop(columns=['name'])

   latitude  longitude country  population  city_id
0   52.5167    13.3833      DE     3644826        1
1   53.5500    10.0000      DE     1841179        2
2   50.1136     8.6797      DE      753056        3
3   48.1372    11.5755      DE     1471508        4
4   50.9422     6.9578      DE     1085664        5

In [12]:
upload_df_fact = upload_df_fact.drop(columns=['name'], errors='ignore') # caused an error due to name column removal
upload_df_fact.to_sql('fact_list', if_exists='append', con=engine, index=False)
print("✅ Success! Foreign keys linked using dictionary map and fact_list is fully populated.")

✅ Success! Foreign keys linked using dictionary map and fact_list is fully populated.

## Now getting the weather information using the latitude and longitude columns

In [13]:
url = "https://api.openweathermap.org/data/2.5/forecast"

params = {
    "lat": 52.5167,
    "lon": 13.3833,
    "appid": "YOUR_API_KEY",
    "units": "metric",
    "mode": "json"
}

weather = requests.get(url=url, params=params)
weather

In [14]:
print(weather.status_code)
print(weather.url)

200
https://api.openweathermap.org/data/2.5/forecast?lat=52.5167&lon=13.3833&appid=YOUR_API_KEY&units=metric&mode=json

In [15]:
weather_json=weather.json()
weather_json

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1784905200,
   'main': {'temp': 23.18,
    'feels_like': 22.75,
    'temp_min': 23.18,
    'temp_max': 24.02,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1009,
    'humidity': 46,
    'temp_kf': -0.84,
    'dew_point': 10.93},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 17},
   'wind': {'speed': 3.73, 'deg': 279, 'gust': 4.42},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-24 15:00:00'},
  {'dt': 1784916000,
   'main': {'temp': 22.48,
    'feels_like': 21.91,
    'temp_min': 22.34,
    'temp_max': 22.48,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 1008,
    'humidity': 43,
    'temp_kf': 0.14,
    'dew_point': 9.29},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 29},
   'wind': {'speed': 2.44, 'deg': 255, 'gust': 3.85},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-24 18:00:00'},
  {'dt': 1784926800,
   'main': {'temp': 18.24,
    'feels_like': 17.4,
    'temp_min': 18.24,
    'temp_max': 18.24,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1008,
    'humidity': 49,
    'temp_kf': 0,
    'dew_point': 8.08},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 88},
   'wind': {'speed': 2.54, 'deg': 233, 'gust': 6},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-07-24 21:00:00'},
  {'dt': 1784937600,
   'main': {'temp': 16.03,
    'feels_like': 15.28,
    'temp_min': 16.03,
    'temp_max': 16.03,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1007,
    'humidity': 61,
    'temp_kf': 0,
    'dew_point': 8.77},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 57},
   'wind': {'speed': 1.84, 'deg': 266, 'gust': 2.9},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-07-25 00:00:00'},
  {'dt': 1784948400,
   'main': {'temp': 15.11,
    'feels_like': 14.48,
    'temp_min': 15.11,
    'temp_max': 15.11,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1006,
    'humidity': 69,
    'temp_kf': 0,
    'dew_point': 9.81},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 92},
   'wind': {'speed': 1.68, 'deg': 254, 'gust': 2.64},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-07-25 03:00:00'},
  {'dt': 1784959200,
   'main': {'temp': 18.69,
    'feels_like': 18.21,
    'temp_min': 18.69,
    'temp_max': 18.69,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1005,
    'humidity': 61,
    'temp_kf': 0,
    'dew_point': 10.52},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 93},
   'wind': {'speed': 1.73, 'deg': 225, 'gust': 2.79},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-25 06:00:00'},
  {'dt': 1784970000,
   'main': {'temp': 24.45,
    'feels_like': 23.92,
    'temp_min': 24.45,
    'temp_max': 24.45,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 1004,
    'humidity': 37,
    'temp_kf': 0,
    'dew_point': 8.28},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 68},
   'wind': {'speed': 2.68, 'deg': 203, 'gust': 3.74},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-25 09:00:00'},
  {'dt': 1784980800,
   'main': {'temp': 27.64,
    'feels_like': 26.76,
    'temp_min': 27.64,
    'temp_max': 27.64,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 1002,
    'humidity': 28,
    'temp_kf': 0,
    'dew_point': 7.83},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 41},
   'wind': {'speed': 3.4, 'deg': 219, 'gust': 5.19},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-25 12:00:00'},
  {'dt': 1784991600,
   'main': {'temp': 29.25,
    'feels_like': 27.87,
    'temp_min': 29.25,
    'temp_max': 29.25,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 1000,
    'humidity': 26,
    'temp_kf': 0,
    'dew_point': 7.76},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 13},
   'wind': {'speed': 4.15, 'deg': 264, 'gust': 5.35},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-25 15:00:00'},
  {'dt': 1785002400,
   'main': {'temp': 26.33,
    'feels_like': 26.33,
    'temp_min': 26.33,
    'temp_max': 26.33,
    'pressure': 1004,
    'sea_level': 1004,
    'grnd_level': 999,
    'humidity': 35,
    'temp_kf': 0,
    'dew_point': 9.95},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 16},
   'wind': {'speed': 3.54, 'deg': 263, 'gust': 6.13},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-25 18:00:00'},
  {'dt': 1785013200,
   'main': {'temp': 22.58,
    'feels_like': 22.09,
    'temp_min': 22.58,
    'temp_max': 22.58,
    'pressure': 1004,
    'sea_level': 1004,
    'grnd_level': 998,
    'humidity': 46,
    'temp_kf': 0,
    'dew_point': 10.68},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 2},
   'wind': {'speed': 1.9, 'deg': 234, 'gust': 2.94},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-07-25 21:00:00'},
  {'dt': 1785024000,
   'main': {'temp': 20.05,
    'feels_like': 19.6,
    'temp_min': 20.05,
    'temp_max': 20.05,
    'pressure': 1004,
    'sea_level': 1004,
    'grnd_level': 998,
    'humidity': 57,
    'temp_kf': 0,
    'dew_point': 11.48},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 11},
   'wind': {'speed': 2.53, 'deg': 276, 'gust': 5.94},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-07-26 00:00:00'},
  {'dt': 1785034800,
   'main': {'temp': 18.77,
    'feels_like': 18.09,
    'temp_min': 18.77,
    'temp_max': 18.77,
    'pressure': 1004,
    'sea_level': 1004,
    'grnd_level': 999,
    'humidity': 53,
    'temp_kf': 0,
    'dew_point': 9.16},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.98, 'deg': 314, 'gust': 6.89},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-07-26 03:00:00'},
  {'dt': 1785045600,
   'main': {'temp': 20,
    'feels_like': 19.33,
    'temp_min': 20,
    'temp_max': 20,
    'pressure': 1004,
    'sea_level': 1004,
    'grnd_level': 999,
    'humidity': 49,
    'temp_kf': 0,
    'dew_point': 8.62},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 99},
   'wind': {'speed': 2.35, 'deg': 319, 'gust': 3.96},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-26 06:00:00'},
  {'dt': 1785056400,
   'main': {'temp': 23.17,
    'feels_like': 22.59,
    'temp_min': 23.17,
    'temp_max': 23.17,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 1000,
    'humidity': 40,
    'temp_kf': 0,
    'dew_point': 8.9},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.86, 'deg': 275, 'gust': 2.93},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-26 09:00:00'},
  {'dt': 1785067200,
   'main': {'temp': 21.49,
    'feels_like': 20.95,
    'temp_min': 21.49,
    'temp_max': 21.49,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 1000,
    'humidity': 48,
    'temp_kf': 0,
    'dew_point': 9.92},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.24, 'deg': 294, 'gust': 5.07},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-26 12:00:00'},
  {'dt': 1785078000,
   'main': {'temp': 17.56,
    'feels_like': 17.49,
    'temp_min': 17.56,
    'temp_max': 17.56,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 1001,
    'humidity': 81,
    'temp_kf': 0,
    'dew_point': 14.14},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 4.29, 'deg': 288, 'gust': 11.19},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 1.26},
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-26 15:00:00'},
  {'dt': 1785088800,
   'main': {'temp': 18.04,
    'feels_like': 18.01,
    'temp_min': 18.04,
    'temp_max': 18.04,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 1000,
    'humidity': 81,
    'temp_kf': 0,
    'dew_point': 14.63},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 98},
   'wind': {'speed': 3.26, 'deg': 233, 'gust': 7.89},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 0.93},
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-26 18:00:00'},
  {'dt': 1785099600,
   'main': {'temp': 17.03,
    'feels_like': 17.09,
    'temp_min': 17.03,
    'temp_max': 17.03,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 1000,
    'humidity': 88,
    'temp_kf': 0,
    'dew_point': 15.04},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 97},
   'wind': {'speed': 3.55, 'deg': 220, 'gust': 8.81},
   'visibility': 10000,
   'pop': 0.32,
   'rain': {'3h': 0.26},
   'sys': {'pod': 'n'},
   'dt_txt': '2026-07-26 21:00:00'},
  {'dt': 1785110400,
   'main': {'temp': 16.79,
    'feels_like': 16.8,
    'temp_min': 16.79,
    'temp_max': 16.79,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 1000,
    'humidity': 87,
    'temp_kf': 0,
    'dew_point': 14.67},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 95},
   'wind': {'speed': 3.57, 'deg': 240, 'gust': 9.75},
   'visibility': 10000,
   'pop': 0.64,
   'rain': {'3h': 0.39},
   'sys': {'pod': 'n'},
   'dt_txt': '2026-07-27 00:00:00'},
  {'dt': 1785121200,
   'main': {'temp': 15.63,
    'feels_like': 15.7,
    'temp_min': 15.63,
    'temp_max': 15.63,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 1002,
    'humidity': 94,
    'temp_kf': 0,
    'dew_point': 14.6},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 88},
   'wind': {'speed': 4.46, 'deg': 275, 'gust': 9.62},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 0.99},
   'sys': {'pod': 'n'},
   'dt_txt': '2026-07-27 03:00:00'},
  {'dt': 1785132000,
   'main': {'temp': 16.4,
    'feels_like': 16.29,
    'temp_min': 16.4,
    'temp_max': 16.4,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1004,
    'humidity': 84,
    'temp_kf': 0,
    'dew_point': 13.75},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 86},
   'wind': {'speed': 4.89, 'deg': 292, 'gust': 10.33},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 0.36},
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-27 06:00:00'},
  {'dt': 1785142800,
   'main': {'temp': 19.6,
    'feels_like': 18.97,
    'temp_min': 19.6,
    'temp_max': 19.6,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1007,
    'humidity': 52,
    'temp_kf': 0,
    'dew_point': 9.53},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 41},
   'wind': {'speed': 6.42, 'deg': 301, 'gust': 9.18},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-27 09:00:00'},
  {'dt': 1785153600,
   'main': {'temp': 22.63,
    'feels_like': 21.81,
    'temp_min': 22.63,
    'temp_max': 22.63,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 1009,
    'humidity': 33,
    'temp_kf': 0,
    'dew_point': 5.55},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 23},
   'wind': {'speed': 6.45, 'deg': 305, 'gust': 8.84},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-27 12:00:00'},
  {'dt': 1785164400,
   'main': {'temp': 23.73,
    'feels_like': 22.92,
    'temp_min': 23.73,
    'temp_max': 23.73,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1010,
    'humidity': 29,
    'temp_kf': 0,
    'dew_point': 4.72},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 4},
   'wind': {'speed': 6.01, 'deg': 305, 'gust': 8.65},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-27 15:00:00'},
  {'dt': 1785175200,
   'main': {'temp': 21.4,
    'feels_like': 20.59,
    'temp_min': 21.4,
    'temp_max': 21.4,
    'pressure': 1017,
    'sea_level': 1017,
    'grnd_level': 1012,
    'humidity': 38,
    'temp_kf': 0,
    'dew_point': 6.66},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 8},
   'wind': {'speed': 4.92, 'deg': 309, 'gust': 8.04},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-27 18:00:00'},
  {'dt': 1785186000,
   'main': {'temp': 17.8,
    'feels_like': 17.05,
    'temp_min': 17.8,
    'temp_max': 17.8,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 1013,
    'humidity': 54,
    'temp_kf': 0,
    'dew_point': 8.26},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 9},
   'wind': {'speed': 2.82, 'deg': 306, 'gust': 7.61},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-07-27 21:00:00'},
  {'dt': 1785196800,
   'main': {'temp': 16.67,
    'feels_like': 15.96,
    'temp_min': 16.67,
    'temp_max': 16.67,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 1014,
    'humidity': 60,
    'temp_kf': 0,
    'dew_point': 8.85},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 26},
   'wind': {'speed': 2.65, 'deg': 295, 'gust': 6.26},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-07-28 00:00:00'},
  {'dt': 1785207600,
   'main': {'temp': 14.91,
    'feels_like': 14.23,
    'temp_min': 14.91,
    'temp_max': 14.91,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1015,
    'humidity': 68,
    'temp_kf': 0,
    'dew_point': 9.14},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 6},
   'wind': {'speed': 1.74, 'deg': 284, 'gust': 3.43},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-07-28 03:00:00'},
  {'dt': 1785218400,
   'main': {'temp': 17.6,
    'feels_like': 16.98,
    'temp_min': 17.6,
    'temp_max': 17.6,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1016,
    'humidity': 60,
    'temp_kf': 0,
    'dew_point': 9.63},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 8},
   'wind': {'speed': 2.29, 'deg': 249, 'gust': 3.92},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-28 06:00:00'},
  {'dt': 1785229200,
   'main': {'temp': 22.39,
    'feels_like': 21.89,
    'temp_min': 22.39,
    'temp_max': 22.39,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1016,
    'humidity': 46,
    'temp_kf': 0,
    'dew_point': 10.26},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 49},
   'wind': {'speed': 4.05, 'deg': 268, 'gust': 5.93},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-28 09:00:00'},
  {'dt': 1785240000,
   'main': {'temp': 25.87,
    'feels_like': 25.53,
    'temp_min': 25.87,
    'temp_max': 25.87,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1015,
    'humidity': 39,
    'temp_kf': 0,
    'dew_point': 10.93},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 48},
   'wind': {'speed': 3.99, 'deg': 291, 'gust': 5.3},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-28 12:00:00'},
  {'dt': 1785250800,
   'main': {'temp': 27.32,
    'feels_like': 26.95,
    'temp_min': 27.32,
    'temp_max': 27.32,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 1015,
    'humidity': 37,
    'temp_kf': 0,
    'dew_point': 11.38},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 22},
   'wind': {'speed': 3.08, 'deg': 295, 'gust': 4.17},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-28 15:00:00'},
  {'dt': 1785261600,
   'main': {'temp': 25.93,
    'feels_like': 25.68,
    'temp_min': 25.93,
    'temp_max': 25.93,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1015,
    'humidity': 42,
    'temp_kf': 0,
    'dew_point': 12.28},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 15},
   'wind': {'speed': 1.21, 'deg': 291, 'gust': 2.15},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-07-28 18:00:00'},
  {'dt': 1785272400,
   'main': {'temp': 22.81,
    'feels_like': 22.48,
    'temp_min': 22.81,
    'temp_max': 22.81,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1016,
    'humidity': 51,
    'temp_kf': 0,
    'dew_point': 12.25},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 68},
   'wind': {'speed': 0.66, 'deg': 100, 'gust': 0.81},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-07-28 21:00:00'},
  {'dt': 1785283200,
   'main': {'temp': 20.81,
    'feels_like': 20.46,
    'temp_min': 20.81,
    'temp_max': 20.81,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1016,
    'humidity': 58,
    'temp_kf': 0,
    'dew_point': 12.29},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 76},
   'wind': {'speed': 1.8, 'deg': 153, 'gust': 2.23},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-07-29 00:00:00'},
  {'dt': 1785294000,
   'main': {'temp': 19.43,
    'feels_like': 19.05,
    'temp_min': 19.43,
    'temp_max': 19.43,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1015,
    'humidity': 62,
    'temp_kf': 0,
    'dew_point': 12.01},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 50},
   'wind': {'speed': 2.23, 'deg': 148, 'gust': 4.05},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},

In [16]:
weather_json.keys()

dict_keys(['cod', 'message', 'cnt', 'list', 'city'])

In [17]:
weather_json['list']

[{'dt': 1784905200,
  'main': {'temp': 23.18,
   'feels_like': 22.75,
   'temp_min': 23.18,
   'temp_max': 24.02,
   'pressure': 1015,
   'sea_level': 1015,
   'grnd_level': 1009,
   'humidity': 46,
   'temp_kf': -0.84,
   'dew_point': 10.93},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 17},
  'wind': {'speed': 3.73, 'deg': 279, 'gust': 4.42},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-24 15:00:00'},
 {'dt': 1784916000,
  'main': {'temp': 22.48,
   'feels_like': 21.91,
   'temp_min': 22.34,
   'temp_max': 22.48,
   'pressure': 1014,
   'sea_level': 1014,
   'grnd_level': 1008,
   'humidity': 43,
   'temp_kf': 0.14,
   'dew_point': 9.29},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 29},
  'wind': {'speed': 2.44, 'deg': 255, 'gust': 3.85},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-24 18:00:00'},
 {'dt': 1784926800,
  'main': {'temp': 18.24,
   'feels_like': 17.4,
   'temp_min': 18.24,
   'temp_max': 18.24,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1008,
   'humidity': 49,
   'temp_kf': 0,
   'dew_point': 8.08},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 88},
  'wind': {'speed': 2.54, 'deg': 233, 'gust': 6},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-07-24 21:00:00'},
 {'dt': 1784937600,
  'main': {'temp': 16.03,
   'feels_like': 15.28,
   'temp_min': 16.03,
   'temp_max': 16.03,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1007,
   'humidity': 61,
   'temp_kf': 0,
   'dew_point': 8.77},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 57},
  'wind': {'speed': 1.84, 'deg': 266, 'gust': 2.9},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-07-25 00:00:00'},
 {'dt': 1784948400,
  'main': {'temp': 15.11,
   'feels_like': 14.48,
   'temp_min': 15.11,
   'temp_max': 15.11,
   'pressure': 1012,
   'sea_level': 1012,
   'grnd_level': 1006,
   'humidity': 69,
   'temp_kf': 0,
   'dew_point': 9.81},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 92},
  'wind': {'speed': 1.68, 'deg': 254, 'gust': 2.64},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-07-25 03:00:00'},
 {'dt': 1784959200,
  'main': {'temp': 18.69,
   'feels_like': 18.21,
   'temp_min': 18.69,
   'temp_max': 18.69,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 1005,
   'humidity': 61,
   'temp_kf': 0,
   'dew_point': 10.52},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 93},
  'wind': {'speed': 1.73, 'deg': 225, 'gust': 2.79},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-25 06:00:00'},
 {'dt': 1784970000,
  'main': {'temp': 24.45,
   'feels_like': 23.92,
   'temp_min': 24.45,
   'temp_max': 24.45,
   'pressure': 1009,
   'sea_level': 1009,
   'grnd_level': 1004,
   'humidity': 37,
   'temp_kf': 0,
   'dew_point': 8.28},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 68},
  'wind': {'speed': 2.68, 'deg': 203, 'gust': 3.74},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-25 09:00:00'},
 {'dt': 1784980800,
  'main': {'temp': 27.64,
   'feels_like': 26.76,
   'temp_min': 27.64,
   'temp_max': 27.64,
   'pressure': 1007,
   'sea_level': 1007,
   'grnd_level': 1002,
   'humidity': 28,
   'temp_kf': 0,
   'dew_point': 7.83},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 41},
  'wind': {'speed': 3.4, 'deg': 219, 'gust': 5.19},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-25 12:00:00'},
 {'dt': 1784991600,
  'main': {'temp': 29.25,
   'feels_like': 27.87,
   'temp_min': 29.25,
   'temp_max': 29.25,
   'pressure': 1005,
   'sea_level': 1005,
   'grnd_level': 1000,
   'humidity': 26,
   'temp_kf': 0,
   'dew_point': 7.76},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 13},
  'wind': {'speed': 4.15, 'deg': 264, 'gust': 5.35},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-25 15:00:00'},
 {'dt': 1785002400,
  'main': {'temp': 26.33,
   'feels_like': 26.33,
   'temp_min': 26.33,
   'temp_max': 26.33,
   'pressure': 1004,
   'sea_level': 1004,
   'grnd_level': 999,
   'humidity': 35,
   'temp_kf': 0,
   'dew_point': 9.95},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 16},
  'wind': {'speed': 3.54, 'deg': 263, 'gust': 6.13},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-25 18:00:00'},
 {'dt': 1785013200,
  'main': {'temp': 22.58,
   'feels_like': 22.09,
   'temp_min': 22.58,
   'temp_max': 22.58,
   'pressure': 1004,
   'sea_level': 1004,
   'grnd_level': 998,
   'humidity': 46,
   'temp_kf': 0,
   'dew_point': 10.68},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 2},
  'wind': {'speed': 1.9, 'deg': 234, 'gust': 2.94},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-07-25 21:00:00'},
 {'dt': 1785024000,
  'main': {'temp': 20.05,
   'feels_like': 19.6,
   'temp_min': 20.05,
   'temp_max': 20.05,
   'pressure': 1004,
   'sea_level': 1004,
   'grnd_level': 998,
   'humidity': 57,
   'temp_kf': 0,
   'dew_point': 11.48},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'clouds': {'all': 11},
  'wind': {'speed': 2.53, 'deg': 276, 'gust': 5.94},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-07-26 00:00:00'},
 {'dt': 1785034800,
  'main': {'temp': 18.77,
   'feels_like': 18.09,
   'temp_min': 18.77,
   'temp_max': 18.77,
   'pressure': 1004,
   'sea_level': 1004,
   'grnd_level': 999,
   'humidity': 53,
   'temp_kf': 0,
   'dew_point': 9.16},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.98, 'deg': 314, 'gust': 6.89},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-07-26 03:00:00'},
 {'dt': 1785045600,
  'main': {'temp': 20,
   'feels_like': 19.33,
   'temp_min': 20,
   'temp_max': 20,
   'pressure': 1004,
   'sea_level': 1004,
   'grnd_level': 999,
   'humidity': 49,
   'temp_kf': 0,
   'dew_point': 8.62},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 99},
  'wind': {'speed': 2.35, 'deg': 319, 'gust': 3.96},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-26 06:00:00'},
 {'dt': 1785056400,
  'main': {'temp': 23.17,
   'feels_like': 22.59,
   'temp_min': 23.17,
   'temp_max': 23.17,
   'pressure': 1005,
   'sea_level': 1005,
   'grnd_level': 1000,
   'humidity': 40,
   'temp_kf': 0,
   'dew_point': 8.9},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 1.86, 'deg': 275, 'gust': 2.93},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-26 09:00:00'},
 {'dt': 1785067200,
  'main': {'temp': 21.49,
   'feels_like': 20.95,
   'temp_min': 21.49,
   'temp_max': 21.49,
   'pressure': 1005,
   'sea_level': 1005,
   'grnd_level': 1000,
   'humidity': 48,
   'temp_kf': 0,
   'dew_point': 9.92},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 3.24, 'deg': 294, 'gust': 5.07},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-26 12:00:00'},
 {'dt': 1785078000,
  'main': {'temp': 17.56,
   'feels_like': 17.49,
   'temp_min': 17.56,
   'temp_max': 17.56,
   'pressure': 1006,
   'sea_level': 1006,
   'grnd_level': 1001,
   'humidity': 81,
   'temp_kf': 0,
   'dew_point': 14.14},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.29, 'deg': 288, 'gust': 11.19},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 1.26},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-26 15:00:00'},
 {'dt': 1785088800,
  'main': {'temp': 18.04,
   'feels_like': 18.01,
   'temp_min': 18.04,
   'temp_max': 18.04,
   'pressure': 1005,
   'sea_level': 1005,
   'grnd_level': 1000,
   'humidity': 81,
   'temp_kf': 0,
   'dew_point': 14.63},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 98},
  'wind': {'speed': 3.26, 'deg': 233, 'gust': 7.89},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 0.93},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-26 18:00:00'},
 {'dt': 1785099600,
  'main': {'temp': 17.03,
   'feels_like': 17.09,
   'temp_min': 17.03,
   'temp_max': 17.03,
   'pressure': 1006,
   'sea_level': 1006,
   'grnd_level': 1000,
   'humidity': 88,
   'temp_kf': 0,
   'dew_point': 15.04},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 97},
  'wind': {'speed': 3.55, 'deg': 220, 'gust': 8.81},
  'visibility': 10000,
  'pop': 0.32,
  'rain': {'3h': 0.26},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-07-26 21:00:00'},
 {'dt': 1785110400,
  'main': {'temp': 16.79,
   'feels_like': 16.8,
   'temp_min': 16.79,
   'temp_max': 16.79,
   'pressure': 1006,
   'sea_level': 1006,
   'grnd_level': 1000,
   'humidity': 87,
   'temp_kf': 0,
   'dew_point': 14.67},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 95},
  'wind': {'speed': 3.57, 'deg': 240, 'gust': 9.75},
  'visibility': 10000,
  'pop': 0.64,
  'rain': {'3h': 0.39},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-07-27 00:00:00'},
 {'dt': 1785121200,
  'main': {'temp': 15.63,
   'feels_like': 15.7,
   'temp_min': 15.63,
   'temp_max': 15.63,
   'pressure': 1007,
   'sea_level': 1007,
   'grnd_level': 1002,
   'humidity': 94,
   'temp_kf': 0,
   'dew_point': 14.6},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 88},
  'wind': {'speed': 4.46, 'deg': 275, 'gust': 9.62},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 0.99},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-07-27 03:00:00'},
 {'dt': 1785132000,
  'main': {'temp': 16.4,
   'feels_like': 16.29,
   'temp_min': 16.4,
   'temp_max': 16.4,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1004,
   'humidity': 84,
   'temp_kf': 0,
   'dew_point': 13.75},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 86},
  'wind': {'speed': 4.89, 'deg': 292, 'gust': 10.33},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 0.36},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-27 06:00:00'},
 {'dt': 1785142800,
  'main': {'temp': 19.6,
   'feels_like': 18.97,
   'temp_min': 19.6,
   'temp_max': 19.6,
   'pressure': 1012,
   'sea_level': 1012,
   'grnd_level': 1007,
   'humidity': 52,
   'temp_kf': 0,
   'dew_point': 9.53},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 41},
  'wind': {'speed': 6.42, 'deg': 301, 'gust': 9.18},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-27 09:00:00'},
 {'dt': 1785153600,
  'main': {'temp': 22.63,
   'feels_like': 21.81,
   'temp_min': 22.63,
   'temp_max': 22.63,
   'pressure': 1014,
   'sea_level': 1014,
   'grnd_level': 1009,
   'humidity': 33,
   'temp_kf': 0,
   'dew_point': 5.55},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 23},
  'wind': {'speed': 6.45, 'deg': 305, 'gust': 8.84},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-27 12:00:00'},
 {'dt': 1785164400,
  'main': {'temp': 23.73,
   'feels_like': 22.92,
   'temp_min': 23.73,
   'temp_max': 23.73,
   'pressure': 1015,
   'sea_level': 1015,
   'grnd_level': 1010,
   'humidity': 29,
   'temp_kf': 0,
   'dew_point': 4.72},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 4},
  'wind': {'speed': 6.01, 'deg': 305, 'gust': 8.65},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-27 15:00:00'},
 {'dt': 1785175200,
  'main': {'temp': 21.4,
   'feels_like': 20.59,
   'temp_min': 21.4,
   'temp_max': 21.4,
   'pressure': 1017,
   'sea_level': 1017,
   'grnd_level': 1012,
   'humidity': 38,
   'temp_kf': 0,
   'dew_point': 6.66},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 8},
  'wind': {'speed': 4.92, 'deg': 309, 'gust': 8.04},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-27 18:00:00'},
 {'dt': 1785186000,
  'main': {'temp': 17.8,
   'feels_like': 17.05,
   'temp_min': 17.8,
   'temp_max': 17.8,
   'pressure': 1019,
   'sea_level': 1019,
   'grnd_level': 1013,
   'humidity': 54,
   'temp_kf': 0,
   'dew_point': 8.26},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 9},
  'wind': {'speed': 2.82, 'deg': 306, 'gust': 7.61},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-07-27 21:00:00'},
 {'dt': 1785196800,
  'main': {'temp': 16.67,
   'feels_like': 15.96,
   'temp_min': 16.67,
   'temp_max': 16.67,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1014,
   'humidity': 60,
   'temp_kf': 0,
   'dew_point': 8.85},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 26},
  'wind': {'speed': 2.65, 'deg': 295, 'gust': 6.26},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-07-28 00:00:00'},
 {'dt': 1785207600,
  'main': {'temp': 14.91,
   'feels_like': 14.23,
   'temp_min': 14.91,
   'temp_max': 14.91,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1015,
   'humidity': 68,
   'temp_kf': 0,
   'dew_point': 9.14},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 6},
  'wind': {'speed': 1.74, 'deg': 284, 'gust': 3.43},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-07-28 03:00:00'},
 {'dt': 1785218400,
  'main': {'temp': 17.6,
   'feels_like': 16.98,
   'temp_min': 17.6,
   'temp_max': 17.6,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1016,
   'humidity': 60,
   'temp_kf': 0,
   'dew_point': 9.63},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 8},
  'wind': {'speed': 2.29, 'deg': 249, 'gust': 3.92},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-28 06:00:00'},
 {'dt': 1785229200,
  'main': {'temp': 22.39,
   'feels_like': 21.89,
   'temp_min': 22.39,
   'temp_max': 22.39,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1016,
   'humidity': 46,
   'temp_kf': 0,
   'dew_point': 10.26},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 49},
  'wind': {'speed': 4.05, 'deg': 268, 'gust': 5.93},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-28 09:00:00'},
 {'dt': 1785240000,
  'main': {'temp': 25.87,
   'feels_like': 25.53,
   'temp_min': 25.87,
   'temp_max': 25.87,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1015,
   'humidity': 39,
   'temp_kf': 0,
   'dew_point': 10.93},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 48},
  'wind': {'speed': 3.99, 'deg': 291, 'gust': 5.3},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-28 12:00:00'},
 {'dt': 1785250800,
  'main': {'temp': 27.32,
   'feels_like': 26.95,
   'temp_min': 27.32,
   'temp_max': 27.32,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1015,
   'humidity': 37,
   'temp_kf': 0,
   'dew_point': 11.38},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 22},
  'wind': {'speed': 3.08, 'deg': 295, 'gust': 4.17},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-28 15:00:00'},
 {'dt': 1785261600,
  'main': {'temp': 25.93,
   'feels_like': 25.68,
   'temp_min': 25.93,
   'temp_max': 25.93,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1015,
   'humidity': 42,
   'temp_kf': 0,
   'dew_point': 12.28},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 15},
  'wind': {'speed': 1.21, 'deg': 291, 'gust': 2.15},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-28 18:00:00'},
 {'dt': 1785272400,
  'main': {'temp': 22.81,
   'feels_like': 22.48,
   'temp_min': 22.81,
   'temp_max': 22.81,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1016,
   'humidity': 51,
   'temp_kf': 0,
   'dew_point': 12.25},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 68},
  'wind': {'speed': 0.66, 'deg': 100, 'gust': 0.81},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-07-28 21:00:00'},
 {'dt': 1785283200,
  'main': {'temp': 20.81,
   'feels_like': 20.46,
   'temp_min': 20.81,
   'temp_max': 20.81,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1016,
   'humidity': 58,
   'temp_kf': 0,
   'dew_point': 12.29},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 76},
  'wind': {'speed': 1.8, 'deg': 153, 'gust': 2.23},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-07-29 00:00:00'},
 {'dt': 1785294000,
  'main': {'temp': 19.43,
   'feels_like': 19.05,
   'temp_min': 19.43,
   'temp_max': 19.43,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1015,
   'humidity': 62,
   'temp_kf': 0,
   'dew_point': 12.01},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 50},
  'wind': {'speed': 2.23, 'deg': 148, 'gust': 4.05},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-07-29 03:00:00'},
 {'dt': 1785304800,
  'main': {'temp': 22.13,
   'feels_like': 21.81,
   'temp_min': 22.13,
   'temp_max': 22.13,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1015,
   'humidity': 54,
   'temp_kf': 0,
   'dew_point': 12.39},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 72},
  'wind': {'speed': 3.02, 'deg': 151, 'gust': 5.25},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-07-29 06:00:00'},
 {'dt': 1785315600,
  'main': {'temp': 28.19,
   'feels_like': 27.57,
   'temp_min': 28.19,
   'temp_max': 28.19,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1014,
   'humidity': 36,
   'temp_kf': 0,
   'dew_point': 11.87},
  'weather': [{'id': 803,
    'main': 'Clouds',

In [18]:
weather_json['city']

{'id': 2822234,
 'name': 'Tiergarten',
 'coord': {'lat': 52.5167, 'lon': 13.3833},
 'country': 'DE',
 'population': 0,
 'timezone': 7200,
 'sunrise': 1784862814,
 'sunset': 1784920323}

In [19]:
weather_json_df = pd.json_normalize(weather_json)
weather_json_df

   cod  message  cnt                                               list  city.id   city.name  city.coord.lat  city.coord.lon city.country  city.population  city.timezone  city.sunrise  city.sunset
0  200        0   40  [{'dt': 1784905200, 'main': {'temp': 23.18, 'f...  2822234  Tiergarten         52.5167         13.3833           DE                0           7200    1784862814   1784920323

1.Extracting the wind speed list

In [20]:
wind_speeds = []
for forecast in weather_json['list']:
    speed = forecast['wind']['speed']
    wind_speeds.append(speed)
print(wind_speeds)

[3.73, 2.44, 2.54, 1.84, 1.68, 1.73, 2.68, 3.4, 4.15, 3.54, 1.9, 2.53, 2.98, 2.35, 1.86, 3.24, 4.29, 3.26, 3.55, 3.57, 4.46, 4.89, 6.42, 6.45, 6.01, 4.92, 2.82, 2.65, 1.74, 2.29, 4.05, 3.99, 3.08, 1.21, 0.66, 1.8, 2.23, 3.02, 3.21, 2.95]

2.Extracting the time

In [21]:
forecast_time = []
for forecast in weather_json['list']:
    time = forecast['dt_txt']
    forecast_time.append(time)
print(forecast_time)

['2026-07-24 15:00:00', '2026-07-24 18:00:00', '2026-07-24 21:00:00', '2026-07-25 00:00:00', '2026-07-25 03:00:00', '2026-07-25 06:00:00', '2026-07-25 09:00:00', '2026-07-25 12:00:00', '2026-07-25 15:00:00', '2026-07-25 18:00:00', '2026-07-25 21:00:00', '2026-07-26 00:00:00', '2026-07-26 03:00:00', '2026-07-26 06:00:00', '2026-07-26 09:00:00', '2026-07-26 12:00:00', '2026-07-26 15:00:00', '2026-07-26 18:00:00', '2026-07-26 21:00:00', '2026-07-27 00:00:00', '2026-07-27 03:00:00', '2026-07-27 06:00:00', '2026-07-27 09:00:00', '2026-07-27 12:00:00', '2026-07-27 15:00:00', '2026-07-27 18:00:00', '2026-07-27 21:00:00', '2026-07-28 00:00:00', '2026-07-28 03:00:00', '2026-07-28 06:00:00', '2026-07-28 09:00:00', '2026-07-28 12:00:00', '2026-07-28 15:00:00', '2026-07-28 18:00:00', '2026-07-28 21:00:00', '2026-07-29 00:00:00', '2026-07-29 03:00:00', '2026-07-29 06:00:00', '2026-07-29 09:00:00', '2026-07-29 12:00:00']

3. Extracting temperature

In [22]:
temperature  = []
for forecast in weather_json['list']:
    temp = forecast['main']['temp']
    temperature.append(temp)
print(temperature)

[23.18, 22.48, 18.24, 16.03, 15.11, 18.69, 24.45, 27.64, 29.25, 26.33, 22.58, 20.05, 18.77, 20, 23.17, 21.49, 17.56, 18.04, 17.03, 16.79, 15.63, 16.4, 19.6, 22.63, 23.73, 21.4, 17.8, 16.67, 14.91, 17.6, 22.39, 25.87, 27.32, 25.93, 22.81, 20.81, 19.43, 22.13, 28.19, 32.05]

4. Extracting forecast

In [23]:
# 1. Changed list name to avoid variable conflicts
forecast = []

for forecast_item in weather_json['list']:
    # 2. Extract description from the nested 'weather' list layer
    description = forecast_item['weather'][0]['main']
    forecast.append(description)

print(forecast)

['Clouds', 'Clouds', 'Clouds', 'Clouds', 'Clouds', 'Clouds', 'Clouds', 'Clouds', 'Clouds', 'Clouds', 'Clear', 'Clouds', 'Clouds', 'Clouds', 'Clouds', 'Clouds', 'Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Clouds', 'Clouds', 'Clear', 'Clear', 'Clear', 'Clouds', 'Clear', 'Clear', 'Clouds', 'Clouds', 'Clouds', 'Clouds', 'Clouds', 'Clouds', 'Clouds', 'Clouds', 'Clouds', 'Clouds']

5. getting the rain

In [24]:
rain_in_last_3h  = []
for forecast in weather_json['list']:
    rain = forecast['pop']
    rain_in_last_3h.append(rain)
print(rain_in_last_3h)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0.32, 0.64, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

6. making the data frame table

In [25]:
# --- Mentor Addition: Force Pandas to display everything on one line without wrapping ---
master_weather_records = []
current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

for item in weather_json["list"]:
    forecast_text = (
        item["weather"][0]["main"] if item.get("weather") else "Unknown"
    )

    master_weather_records.append(
        {
            "city_id": 1,
            "forecast_time": item["dt_txt"],
            "temperature": item["main"]["temp"],
            "forecast": forecast_text,
            "rain_in_last_3h": item.get("pop", 0.0),
            "wind_speed": item["wind"]["speed"],
            "data_retrieved_at": current_time,
        }
    )

weather_df = pd.DataFrame(master_weather_records)

print(f"✅ Success! Flattened table contains {len(weather_df)} records.")
weather_df

✅ Success! Flattened table contains 40 records.

    city_id        forecast_time  temperature forecast  rain_in_last_3h  wind_speed    data_retrieved_at
0         1  2026-07-24 15:00:00        23.18   Clouds             0.00        3.73  2026-07-24 15:28:19
1         1  2026-07-24 18:00:00        22.48   Clouds             0.00        2.44  2026-07-24 15:28:19
2         1  2026-07-24 21:00:00        18.24   Clouds             0.00        2.54  2026-07-24 15:28:19
3         1  2026-07-25 00:00:00        16.03   Clouds             0.00        1.84  2026-07-24 15:28:19
4         1  2026-07-25 03:00:00        15.11   Clouds             0.00        1.68  2026-07-24 15:28:19
5         1  2026-07-25 06:00:00        18.69   Clouds             0.00        1.73  2026-07-24 15:28:19
6         1  2026-07-25 09:00:00        24.45   Clouds             0.00        2.68  2026-07-24 15:28:19
7         1  2026-07-25 12:00:00        27.64   Clouds             0.00        3.40  2026-07-24 15:28:19
8         1  2026-07-25 15:00:00        29.25   Clouds             0.00        4.15  2026-07-24 15:28:19
9         1  2026-07-25 18:00:00        26.33   Clouds             0.00        3.54  2026-07-24 15:28:19
10        1  2026-07-25 21:00:00        22.58    Clear             0.00        1.90  2026-07-24 15:28:19
11        1  2026-07-26 00:00:00        20.05   Clouds             0.00        2.53  2026-07-24 15:28:19
12        1  2026-07-26 03:00:00        18.77   Clouds             0.00        2.98  2026-07-24 15:28:19
13        1  2026-07-26 06:00:00        20.00   Clouds             0.00        2.35  2026-07-24 15:28:19
14        1  2026-07-26 09:00:00        23.17   Clouds             0.00        1.86  2026-07-24 15:28:19
15        1  2026-07-26 12:00:00        21.49   Clouds             0.00        3.24  2026-07-24 15:28:19
16        1  2026-07-26 15:00:00        17.56     Rain             1.00        4.29  2026-07-24 15:28:19
17        1  2026-07-26 18:00:00        18.04     Rain             1.00        3.26  2026-07-24 15:28:19
18        1  2026-07-26 21:00:00        17.03     Rain             0.32        3.55  2026-07-24 15:28:19
19        1  2026-07-27 00:00:00        16.79     Rain             0.64        3.57  2026-07-24 15:28:19
20        1  2026-07-27 03:00:00        15.63     Rain             1.00        4.46  2026-07-24 15:28:19
21        1  2026-07-27 06:00:00        16.40     Rain             1.00        4.89  2026-07-24 15:28:19
22        1  2026-07-27 09:00:00        19.60   Clouds             0.00        6.42  2026-07-24 15:28:19
23        1  2026-07-27 12:00:00        22.63   Clouds             0.00        6.45  2026-07-24 15:28:19
24        1  2026-07-27 15:00:00        23.73    Clear             0.00        6.01  2026-07-24 15:28:19
25        1  2026-07-27 18:00:00        21.40    Clear             0.00        4.92  2026-07-24 15:28:19
26        1  2026-07-27 21:00:00        17.80    Clear             0.00        2.82  2026-07-24 15:28:19
27        1  2026-07-28 00:00:00        16.67   Clouds             0.00        2.65  2026-07-24 15:28:19
28        1  2026-07-28 03:00:00        14.91    Clear             0.00        1.74  2026-07-24 15:28:19
29        1  2026-07-28 06:00:00        17.60    Clear             0.00        2.29  2026-07-24 15:28:19
30        1  2026-07-28 09:00:00        22.39   Clouds             0.00        4.05  2026-07-24 15:28:19
31        1  2026-07-28 12:00:00        25.87   Clouds             0.00        3.99  2026-07-24 15:28:19
32        1  2026-07-28 15:00:00        27.32   Clouds             0.00        3.08  2026-07-24 15:28:19
33        1  2026-07-28 18:00:00        25.93   Clouds             0.00        1.21  2026-07-24 15:28:19
34        1  2026-07-28 21:00:00        22.81   Clouds             0.00        0.66  2026-07-24 15:28:19
35        1  2026-07-29 00:00:00        20.81   Clouds             0.00        1.80  2026-07-24 15:28:19
36        1  2026-07-29 03:00:00        19.43   Clouds             0.00        2.23  2026-07-24 15:28:19
37        1  2026-07-29 06:00:00        22.13   Clouds             0.00        3.02  2026-07-24 15:28:19
38        1  2026-07-29 09:00:00        28.19   Clouds             0.00        3.21  2026-07-24 15:28:19
39        1  2026-07-29 12:00:00        32.05   Clouds             0.00        2.95  2026-07-24 15:28:19

Now a function to use city_id, latitude and longitude to extract the same data files like in weather_df for each city

In [26]:
#Step 1. Read the cities from SQL
schema = "County_city_info_api"

engine = create_engine(
    "mysql+pymysql://root:YOUR_DB_PASSWORD@127.0.0.1:3306/County_city_info_API"
)

query = text("""
SELECT
    city_id,
    latitude,
    longitude
FROM fact_list
""")

cities = pd.read_sql(query, engine)

cities.head()

   city_id  latitude  longitude
0        1   52.5167    13.3833
1        2   53.5500    10.0000
2        3   50.1136     8.6797
3        4   48.1372    11.5755
4        5   50.9422     6.9578

In [27]:
#Step 2. Loop through every city
API_KEY = "YOUR_API_KEY"

url = "https://api.openweathermap.org/data/2.5/forecast"

master_weather_records = []

current_time = datetime.now()

for _, city in cities.iterrows():

    params = {
        "lat": city["latitude"],
        "lon": city["longitude"],
        "appid": API_KEY,
        "units": "metric",
        "mode": "json"
    }

    response = requests.get(url, params=params)

    if response.status_code != 200:
        print(f"Could not retrieve city_id {city['city_id']}")
        continue

    weather_json = response.json()

    for item in weather_json["list"]:

        forecast_text = (
            item["weather"][0]["main"]
            if item.get("weather")
            else "Unknown"
        )

        master_weather_records.append({
            "city_id": int(city["city_id"]),
            "forecast_time": item["dt_txt"],
            "temperature": item["main"]["temp"],
            "forecast": forecast_text,
            "rain_in_last_3h": item.get("pop", 0),
            "wind_speed": item["wind"]["speed"],
            "data_retrieved_at": current_time
        })

print(f"Total forecast records: {len(master_weather_records)}")

Total forecast records: 200

In [28]:
#Step 3. See the data first
weather_df = pd.DataFrame(master_weather_records)

weather_df.head(60)

    city_id        forecast_time  temperature forecast  rain_in_last_3h  wind_speed          data_retrieved_at
0         1  2026-07-24 15:00:00        23.18   Clouds             0.00        3.73 2026-07-24 15:28:19.213510
1         1  2026-07-24 18:00:00        22.48   Clouds             0.00        2.44 2026-07-24 15:28:19.213510
2         1  2026-07-24 21:00:00        18.24   Clouds             0.00        2.54 2026-07-24 15:28:19.213510
3         1  2026-07-25 00:00:00        16.03   Clouds             0.00        1.84 2026-07-24 15:28:19.213510
4         1  2026-07-25 03:00:00        15.11   Clouds             0.00        1.68 2026-07-24 15:28:19.213510
5         1  2026-07-25 06:00:00        18.69   Clouds             0.00        1.73 2026-07-24 15:28:19.213510
6         1  2026-07-25 09:00:00        24.45   Clouds             0.00        2.68 2026-07-24 15:28:19.213510
7         1  2026-07-25 12:00:00        27.64   Clouds             0.00        3.40 2026-07-24 15:28:19.213510
8         1  2026-07-25 15:00:00        29.25   Clouds             0.00        4.15 2026-07-24 15:28:19.213510
9         1  2026-07-25 18:00:00        26.33   Clouds             0.00        3.54 2026-07-24 15:28:19.213510
10        1  2026-07-25 21:00:00        22.58    Clear             0.00        1.90 2026-07-24 15:28:19.213510
11        1  2026-07-26 00:00:00        20.05   Clouds             0.00        2.53 2026-07-24 15:28:19.213510
12        1  2026-07-26 03:00:00        18.77   Clouds             0.00        2.98 2026-07-24 15:28:19.213510
13        1  2026-07-26 06:00:00        20.00   Clouds             0.00        2.35 2026-07-24 15:28:19.213510
14        1  2026-07-26 09:00:00        23.17   Clouds             0.00        1.86 2026-07-24 15:28:19.213510
15        1  2026-07-26 12:00:00        21.49   Clouds             0.00        3.24 2026-07-24 15:28:19.213510
16        1  2026-07-26 15:00:00        17.56     Rain             1.00        4.29 2026-07-24 15:28:19.213510
17        1  2026-07-26 18:00:00        18.04     Rain             1.00        3.26 2026-07-24 15:28:19.213510
18        1  2026-07-26 21:00:00        17.03     Rain             0.32        3.55 2026-07-24 15:28:19.213510
19        1  2026-07-27 00:00:00        16.79     Rain             0.64        3.57 2026-07-24 15:28:19.213510
20        1  2026-07-27 03:00:00        15.63     Rain             1.00        4.46 2026-07-24 15:28:19.213510
21        1  2026-07-27 06:00:00        16.40     Rain             1.00        4.89 2026-07-24 15:28:19.213510
22        1  2026-07-27 09:00:00        19.60   Clouds             0.00        6.42 2026-07-24 15:28:19.213510
23        1  2026-07-27 12:00:00        22.63   Clouds             0.00        6.45 2026-07-24 15:28:19.213510
24        1  2026-07-27 15:00:00        23.73    Clear             0.00        6.01 2026-07-24 15:28:19.213510
25        1  2026-07-27 18:00:00        21.40    Clear             0.00        4.92 2026-07-24 15:28:19.213510
26        1  2026-07-27 21:00:00        17.80    Clear             0.00        2.82 2026-07-24 15:28:19.213510
27        1  2026-07-28 00:00:00        16.67   Clouds             0.00        2.65 2026-07-24 15:28:19.213510
28        1  2026-07-28 03:00:00        14.91    Clear             0.00        1.74 2026-07-24 15:28:19.213510
29        1  2026-07-28 06:00:00        17.60    Clear             0.00        2.29 2026-07-24 15:28:19.213510
30        1  2026-07-28 09:00:00        22.39   Clouds             0.00        4.05 2026-07-24 15:28:19.213510
31        1  2026-07-28 12:00:00        25.87   Clouds             0.00        3.99 2026-07-24 15:28:19.213510
32        1  2026-07-28 15:00:00        27.32   Clouds             0.00        3.08 2026-07-24 15:28:19.213510
33        1  2026-07-28 18:00:00        25.93   Clouds             0.00        1.21 2026-07-24 15:28:19.213510
34        1  2026-07-28 21:00:00        22.81   Clouds             0.00        0.66 2026-07-24 15:28:19.213510
35        1  2026-07-29 00:00:00        20.81   Clouds             0.00        1.80 2026-07-24 15:28:19.213510
36        1  2026-07-29 03:00:00        19.43   Clouds             0.00        2.23 2026-07-24 15:28:19.213510
37        1  2026-07-29 06:00:00        22.13   Clouds             0.00        3.02 2026-07-24 15:28:19.213510
38        1  2026-07-29 09:00:00        28.19   Clouds             0.00        3.21 2026-07-24 15:28:19.213510
39        1  2026-07-29 12:00:00        32.05   Clouds             0.00        2.95 2026-07-24 15:28:19.213510
40        2  2026-07-24 15:00:00        20.00   Clouds             0.00        3.88 2026-07-24 15:28:19.213510
41        2  2026-07-24 18:00:00        19.89   Clouds             0.00        2.66 2026-07-24 15:28:19.213510
42        2  2026-07-24 21:00:00        16.89   Clouds             0.00        0.96 2026-07-24 15:28:19.213510
43        2  2026-07-25 00:00:00        15.18   Clouds             0.00        1.67 2026-07-24 15:28:19.213510
44        2  2026-07-25 03:00:00        14.53   Clouds             0.00        1.45 2026-07-24 15:28:19.213510
45        2  2026-07-25 06:00:00        17.88   Clouds             0.00        2.42 2026-07-24 15:28:19.213510
46        2  2026-07-25 09:00:00        24.53   Clouds             0.00        3.83 2026-07-24 15:28:19.213510
47        2  2026-07-25 12:00:00        28.43   Clouds             0.00        4.97 2026-07-24 15:28:19.213510
48        2  2026-07-25 15:00:00        28.96   Clouds             0.00        6.07 2026-07-24 15:28:19.213510
49        2  2026-07-25 18:00:00        23.88   Clouds             0.00        4.00 2026-07-24 15:28:19.213510
50        2  2026-07-25 21:00:00        18.48   Clouds             0.00        2.48 2026-07-24 15:28:19.213510
51        2  2026-07-26 00:00:00        16.66     Rain             0.20        2.44 2026-07-24 15:28:19.213510
52        2  2026-07-26 03:00:00        16.82     Rain             1.00        2.72 2026-07-24 15:28:19.213510
53        2  2026-07-26 06:00:00        17.64     Rain             0.99        2.63 2026-07-24 15:28:19.213510
54        2  2026-07-26 09:00:00        16.17     Rain             1.00        2.03 2026-07-24 15:28:19.213510
55        2  2026-07-26 12:00:00        15.84     Rain             1.00        0.91 2026-07-24 15:28:19.213510
56        2  2026-07-26 15:00:00        16.39     Rain             1.00        1.99 2026-07-24 15:28:19.213510
57        2  2026-07-26 18:00:00        16.22     Rain             1.00        2.65 2026-07-24 15:28:19.213510
58        2  2026-07-26 21:00:00        15.71     Rain             1.00        2.79 2026-07-24 15:28:19.213510
59        2  2026-07-27 00:00:00        14.16     Rain             0.68        3.41 2026-07-24 15:28:19.213510

In [29]:
weather_df.info() #checking data types to be able to put this in sql or match them eventually

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   city_id            200 non-null    int64
 1   forecast_time      200 non-null    object
 2   temperature        200 non-null    float64
 3   forecast           200 non-null    object
 4   rain_in_last_3h    200 non-null    float64
 5   wind_speed         200 non-null    float64
 6   data_retrieved_at  200 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(1), object(2)
memory usage: 11.1+ KB

In [30]:
#Step 4. Later upload to SQL
weather_df.to_sql(
    "cities_forecast",
    con=engine,
    if_exists="append",
    index=False
)

200

# optional but clean way

wrapping this into a function

In [31]:
import pandas as pd
import requests
from datetime import datetime

API_KEY = "YOUR_API_KEY"
URL = "https://api.openweathermap.org/data/2.5/forecast"

def create_weather_dataframe(cities):
    """
    Fetches the weather forecast for multiple cities and
    returns a DataFrame.
    """

    weather_records = []

    for city in cities.itertuples(index=False):

        params = {
            "lat": city.latitude,
            "lon": city.longitude,
            "appid": API_KEY,
            "units": "metric",
            "mode": "json"
        }

        response = requests.get(URL, params=params)

        if response.status_code != 200:
            print(f"Skipping city_id {city.city_id}")
            continue

        weather_json = response.json()

        retrieved_at = datetime.now()

        for item in weather_json["list"]:

            weather_records.append({
                "city_id": int(city.city_id),
                "forecast_time": item["dt_txt"],
                "temperature": item["main"]["temp"],
                "forecast": item["weather"][0]["main"],
                "rain_in_last_3h": item.get("pop", 0),
                "wind_speed": item["wind"]["speed"],
                "data_retrieved_at": retrieved_at
            })

    weather_df = pd.DataFrame(weather_records)
    weather_df["city_id"] = weather_df["city_id"].astype(int)

    return weather_df

In [32]:
# Read the cities from SQL
cities = pd.read_sql(query, engine)

# Create the weather DataFrame
weather_df = create_weather_dataframe(cities)

# View the result
weather_df.head()

Skipping city_id 1
Skipping city_id 2
Skipping city_id 3
Skipping city_id 4
Skipping city_id 5

KeyError: 'city_id'